from .sentiment import calculate_sentiment
from .tfidf import calculate_tfidf
from .slang import calculate_slang
from .alliteration import calculate_alliteration
from .antonym import calculate_antonym
from .embeddings import calculate_embeddings
from .imageability_concreteness import calculate_imageability_concreteness
from .ner import calculate_ner
from .attributes import calculate_features
